[program:google-mcp]
command=/usr/bin/pnpm exec tsx index.ts
directory=/home/hellcatvn/node/google-mcp
user=hellcatvn
autostart=true
autorestart=true
startretries=3
startsecs=10
redirect_stderr=true
stdout_logfile=/var/log/google-mcp/out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/google-mcp/err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=NODE_ENV="production"

[supervisord]
logfile=/var/log/supervisord/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

